baseURL: "https://may-dzied.github.io"
languageCode: "en-gb"
title: "NCS project website"
theme: "PaperMod"

params:

    disableThemeToggle: true
    hideFooter: true
    hideMeta: true

    homeInfoParams:
        Title: NCS project
        Content: Information

    socialIcons:
        - name: "Instagram"
          url: "<link>"
        - name: "TikTok"
          url: "<link2>"
        - name: "email"
          url: "mailto:<email adress>"
