baseURL: "https://may-dzied.github.io"
languageCode: "en-gb"
title: "NCS project website"
theme: "PaperMod"

params:

    author: "May Dziedziak"
    disableThemeToggle: false
    hideFooter: true
    hideMeta: true

    homeInfoParams:
        Title: NCS project
        Content: Information

    socialIcons:
        - name: "Instagram"
          url: "<link>"
        - name: "TikTok"
          url: "<link2>"
        - name: "email"
          url: "mailto:<email adress>"

    assets:
        favicon16x16: "favicon16.png"            # Logo 16x16 pixels
        favicon32x32: "favicon32.png"            # Logo 32x32 pixels
        apple_touch_icon: "apple-touch-icon.png" # Logo 180x180 i guess
        theme_color: "#ff0000"

    label:
        text: "Home"
        icon: "/apple-touch-icon.png" # Logo highest resolution possible
